---
site_name: Product Security Interview Prep
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Resources: resources.md
theme:
  name: material

repo_name: ajschmitty/prodsec-interview-prep
repo_url: https://github.com/ajschmitty/prodsec-interview-prep
